name: taxcalc-dev
channels:
  - conda-forge
  - pslmodels
dependencies:
- python
- "numpy>=1.14"
- "pandas>=0.23"
- "bokeh>=1.4.0"
- requests
- numba
- pytest
- pytest-pep8
- pytest-xdist
- pycodestyle
- pylint
- coverage
- "paramtools>=0.14.0"
- behresp
- pip
- pip:
  - jupyter-book